TDataFile *TipsData = new TDataFile("Tilchi.tps");
TipsData->WriteString("TilchiTips", "Tip1", "Для того чтобы просмотреть историю статей и запросов, необходимо нажать сочетание клавиш Ctrl+H.");
TipsData->WriteString("TilchiTips", "Tip2", "Настроить внешний вид программы Tilchi можно в Настройках->\"Оформление\".");
TipsData->WriteString("TilchiTips", "Tip3", "Для того чтобы перейти к началу списка слов, необходимо нажать сочетание клавиш Ctrl+Home.");
TipsData->WriteString("TilchiTips", "Tip4", "Для того чтобы выделить словарную статью, необходимо нажать сочетание клавиш Ctrl+A.");
TipsData->WriteString("TilchiTips", "Tip5", "Для того чтобы перевести слово из статьи, необходимо выделить слово и нажать сочетание клавиш Ctrl+Enter.");
TipsData->WriteString("TilchiTips", "Tip6", "Развернуть или свернуть в окно главное окно можно нажав клавишу F11.");
TipsData->WriteString("TilchiTips", "Tip7", "Настроить отображение панелей можно в Настройках->\"Общие\".");
TipsData->WriteString("TilchiTips", "Tip8", "Начать поиск в статье можно нажав сочетание клавиш Ctrl+F.");
TipsData->WriteString("TilchiTips", "Tip9", "Вставить слово в строку поиска можно при нажатии сочетания клавиш Ctrl+V.");
TipsData->WriteString("TilchiTips", "Tip10", "Ввод символов кириллицы с помощью клавиши Alt можно настроить в Настройках->\"Горячие клавиши\".");
TipsData->WriteString("TilchiTips", "Tip11", "Для того чтобы перейти к концу списка слов, необходимо нажать сочетание клавиш Ctrl+End.");
TipsData->WriteString("TilchiTips", "Tip12", "Информацию о лицензии можно просмотреть в диалоге \"О системе\".");
TipsData->WriteString("TilchiTips", "Tip13", "Скопировать выделенный текст из строки поиска можно при нажатии сочетания клавиш Ctrl+C.");
TipsData->WriteString("TilchiTips", "Tip14", "Для того чтобы перевести к следующему совету, необходимо нажать на кнопку на панели \"Совет\".");
TipsData->WriteString("TilchiTips", "Tip15", "По строке поиска можно перемещаться, используя клавиши Home и End.");
TipsData->WriteString("TilchiTips", "Tip16", "Вырезать слово из строки поиска можно при нажатии сочетания клавиш Ctrl+X.");
TipsData->WriteString("TilchiTips", "Tip17", "Для вывода справки необходимо нажать клавишу F1.");
TipsData->WriteString("TilchiTips", "Tip18", "Для того чтобы изменить направление перевода, необходимо нажать сочетание клавиш Ctrl+I.");
TipsData->WriteString("TilchiTips", "Tip19", "Просмотреть условные сокращения можно выбрав \"Показать условные сокращения\" в меню \"Словарная статья\" или нажать сочетание клавиш Ctrl+R.");
TipsData->WriteString("TilchiTips", "Tip20", "Настроить клавиши для запуска системы Tilchi можно в Настройках->\"Горячие клавиши\".");
TStringList *templist = new TStringList();
templist->LoadFromFile("RES\\KR_value.rtf");
TipsData->WriteString("TilchiValues","KR",templist->Text);
templist->LoadFromFile("RES\\RK_value.rtf");
TipsData->WriteString("TilchiValues","RK",templist->Text);
delete TipsData;
delete templist;